//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programm.База
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nameEntities4 : DbContext
    {
        public nameEntities4()
            : base("name=nameEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlackList> BlackLists { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersGroupActivity> UsersGroupActivities { get; set; }
        public virtual DbSet<UsersPrivateActivity> UsersPrivateActivities { get; set; }
        public virtual DbSet<Посещение> Посещение { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
    }
}
