//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programm.База
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string ФИО { get; set; }
        public string НомерТелефона { get; set; }
        public string ДанныеПаспорта { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public string Email { get; set; }
        public string Организация { get; set; }
        public string Фото { get; set; }
    }
}
