//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПриложениеСотрудников.База
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserEntities : DbContext
    {
        private static UserEntities _context;
        public static UserEntities GetContext()
        {
            if (_context == null)
                _context = new UserEntities();
            return _context;
        }
        public UserEntities()
            : base("name=UserEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlackList> BlackLists { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersGroupActivity> UsersGroupActivities { get; set; }
        public virtual DbSet<UsersPrivateActivity> UsersPrivateActivities { get; set; }
        public virtual DbSet<Посещение> Посещение { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
    }
}
