//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПриложениеСотрудников.База
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPrivateActivity
    {
        public int ID { get; set; }
        public System.DateTime ДатаФормирования { get; set; }
        public string ЦельПосещения { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public System.DateTime ДатаОкончания { get; set; }
        public string Подразделение { get; set; }
        public string ФИОСотрудника { get; set; }
        public string Примечание { get; set; }
        public string Файл { get; set; }
        public int Профиль { get; set; }
        public string Статус { get; set; }
    }
}
